---

- include: status.yml

- name: Enable ipv6
  command: esxcli system module parameters set -m tcpip4 -p ipv6=1
  register: output
  
- name: Print output
  debug: var=output.stdout_lines


- include: status.yml
